name: coupons
description: Sharing coupons and deals.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  get_storage: ^2.0.3
  http: ^0.13.3
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.10
  share: ^2.0.4
  toast: ^0.1.5
  simple_animations: ^3.1.1
  image_picker: ^0.8.4
  flutter_launcher_icons: ^0.9.2
  connectivity: ^3.0.6
  like_button: ^2.0.3
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^1.2.3
  rive: ^0.7.28
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  carousel_slider: ^4.0.0
#  google_mobile_ads: ^0.13.4
  flutter_countdown_timer: ^4.1.0
  responsive_grid: ^2.0.0
  change_app_package_name: ^1.0.0
  pagination_view: ^2.0.0
  faker: ^2.0.0
  in_app_purchase: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/rives/
  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/android.png"
  image_path_ios: "assets/icon/ios.png"


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/android.png
  android: true
  ios: true
